fallback_nodes:
    - 'f('
sequence_nodes:
    - 's('              
condition_nodes:
    - 'at station CHARGE1?'
    - 'at station CHARGE2?'
    - 'at station CONVEYOR_HEAVY?'
    - 'at station CONVEYOR_LIGHT?'
    - 'at station DELIVERY?'
parameterized_condition_nodes:
    - 'battery level'
    - 'carried weight'
    - 'carried light'
    - 'carried heavy'
    - 'conveyor light'
    - 'conveyor heavy'
action_nodes:
    - 'idle!'
    - 'charge!'
    - 'move to CHARGE1!'
    - 'move to CHARGE2!'
    - 'move to CONVEYOR_HEAVY!'
    - 'move to CONVEYOR_LIGHT!'
    - 'move to DELIVERY!'
    - 'pick!'
    - 'place!'
up_node:
    - ')'